### ISSUE TITLE
missing first leg

### ISSUE THREAD

**Issue by abyrd** [bliksemlabs/rrrr#1]
reported by @skinkie:

Try to do the following:

Den Helder Spoor 1 to Middelburg

It seems it skips the first route From Den Helder to Rotterdam but shows:
  20116|29|12622    rtd|4 10:10:00    mdb|1 11:44:00 

skinkie@eee ~/sources/bliksem/rrrr $ ./cmd-client.sh 
From:
Den Helder Spoor 1                                         65391  
To:
Middelburg Spoor 1rrrr[9870]: test client starting         65817  
rrrr[9870]: test client number of requests: 1
rrrr[9870]: test client concurrency: 1
rrrr[9870]: test client thread will send 1 requests
rrrr[9870]: test client thread terminating
rrrr[9870]: 1 threads, 1 total requests, 0.177650 sec total time (5.629046 req/sec)
10:10 - 11:44   Rotterdam Centraal Spoor 4 to Middelburg Spoor 1 [100-IC 20116|29|12622 richting Vlissingen]

**Comment by skinkie** [comment]
Quite confident that we are not missing the first leg anymore:

```
A 2 VEHICLES 
R00   -2 -2 walk;walk; Den Helder; 20:07:00; Den Helder; 20:07:00
R00 11592  2 train Intercity (Den Helder <-> Nijmegen IC3000);Nijmegen; Den Helder; 20:34:00; Amsterdam Centraal; 21:48:00
R00   -2 -2 walk;walk; Amsterdam Centraal; 21:48:00; Amsterdam Centraal; 21:48:00
R01 3445 20 train Fyra (Amsterdam Centraal <-> Breda HSN900);Breda; Amsterdam Centraal; 21:55:00; Rotterdam Centraal; 22:36:00
R01   -2 -2 walk;walk; Rotterdam Centraal; 22:36:00; Rotterdam Centraal; 22:36:00
```
