### ISSUE TITLE
Properly begin trip at multiple transit stops

### ISSUE THREAD

**Issue by abyrd** [bliksemlabs/rrrr#120]
Stefan by email:

"Today we were debugging some issue in rrrr. We have the following situation. Given an X/Y coordinate that is close to a stop, this stop is picked as start position. An other close by route is preferred.

There is a transfer relationship between the start-stop and stop of the opposite route, which is better. There is also a transfer between the stop for the opposite route and the forward route which brings us to our destination.

The black dashed line is found. The red dashed line is found. But it does not happen that it takes the blue line after."

Transfers are only expanded once, i.e. transfers are not chained. The first stop reached on the orange line should have transfers to all other stops in the vicinity. Therefore it should be possible to reach the desired stop on the green line by a direct transfer, not by chaining the red and blue transfers.

The real proper way to handle this at the beginning and end of trips would be to select many beginning-stops and transfer directly to all of them from the beginning-coordinate. 

![no-double-transfer](https://cloud.githubusercontent.com/assets/112871/2614281/4607308e-bbe4-11e3-98ad-0d8c3a1f7dee.png)

**Comment by koch-t** [comment]
This is fixed in branch tdata4 #185
