### ISSUE TITLE
Datasets without agency_id in agency.txt not parsed correctly

### ISSUE THREAD

**Issue by ragarwal6397** [bliksemlabs/rrrr#122]
Per the specification document, the agency_id field is optional: https://developers.google.com/transit/gtfs/reference?csw=1#agency_txt___Field_Definitions

However, this condition doesn't seem to be handled properly in the python scripts when trying to generate timetable.dat using one such dataset for the Chicago CTA - http://www.transitchicago.com/downloads/sch_data/google_transit.zip. I made the following change to fix it on my end. Please help review and merge accordingly:

<pre>
diff --git a/scriptsEtc/gtfsdb.py b/scriptsEtc/gtfsdb.py
index 77c71aa..2ba79f2 100755
--- a/scriptsEtc/gtfsdb.py
+++ b/scriptsEtc/gtfsdb.py
@@ -522,8 +522,13 @@ ORDER BY stop_id
         return list(x[0] for x in self.get_cursor().execute( query,() ))
 
     def agency(self,agency_id):
-        query = "SELECT agency_id,agency_name,agency_url,agency_phone,agency_timezone FROM agency WHERE agency_id = ?"
-        res = list(self.get_cursor().execute( query,(agency_id,) ))
+        if agency_id == "__DEFAULT__": # Likely only one entry
+            query = "SELECT agency_id,agency_name,agency_url,agency_phone,agency_timezone FROM agency"
+            res = list(self.get_cursor().execute( query ))
+        else:
+            query = "SELECT agency_id,agency_name,agency_url,agency_phone,agency_timezone FROM agency WHERE agency_id = ?"
+            res = list(self.get_cursor().execute( query,(agency_id,) ))
+
         if len(res) == 0:
             raise Exception('feed error: agency_id not found')
         elif len(res) > 1:
diff --git a/scriptsEtc/timetable.py b/scriptsEtc/timetable.py
index 7da265d..be01730 100755
--- a/scriptsEtc/timetable.py
+++ b/scriptsEtc/timetable.py
@@ -631,15 +631,22 @@ if len(sorted_agencyIds) == 0:
     agencyUrls.append('')
 else:
     for agency_id,agency_name,agency_url,agency_phone,agency_timezone in [db.agency(agencyId) for agencyId,idx in sorted_agencyIds]:
-        agencyIds.append(agency_id)
+        if agency_id == None: # agency_id is an optional value in GTFS
+            agencyIds.append('')
+        else:
+            agencyIds.append(agency_id)
         agencyNames.append(agency_name)
         agencyUrls.append(agency_url)
+
 write_text_comment("AGENCY IDS")
 print "writing out agencyIds to string table"
 loc_agency_ids = write_string_table(agencyIds)
+
 write_text_comment("AGENCY NAMES")
-print "writing out agencyIds to string table"
+print "writing out agencyNames to string table"
 loc_agency_names = write_string_table(agencyNames)
+
+print "writing out agencyUrls to string table"
 write_text_comment("AGENCY URLS")
 loc_agency_urls = write_string_table(agencyUrls)
 
</pre>

**Comment by koch-t** [comment]
Besides merging your PR to master
This has also been accounted for, in the rewritten timetable generator in the soon to replace master dev-branches ansi/tdata4
