### ISSUE TITLE
Investigate: split up timetable.dat in separate files for efficient updates?

### ISSUE THREAD

**Issue by skinkie** [bliksemlabs/rrrr#14]
After time demand groups are implemented we should investigate the filesize of the total file. If this fill ends up more than 8MB compressed it might be a good idea to split up the individual sections.

We could than update and append sections instead of doing a (full) update.

**Comment by koch-t** [comment]
Timedemandgroups compressed < 3 megabytes

**Comment by skinkie** [comment]
Agreed. Also the timetable format allows loading specific data parts, we might need to guard that a bit better.
