### ISSUE TITLE
Investigate slack-times for cross timingpoint transfers

### ISSUE THREAD

**Issue by koch-t** [bliksemlabs/rrrr#15]
Especially when adding timeupdates, we've got to investigate if setting slacktimes to nearly 0 if a transfer occurs from timingpoint to timingpoint within the same stoparea.
Usually it seems busses will wait on each other on timingpoints, not every later departure will be properly communicated via KV17.

**Comment by skinkie** [comment]
This also could make cross platform train transfers extremely valuable.

**Comment by abyrd** [comment]
This is then very closely related to #3 and involves heuristic rules for not adding slack time or transfer cost.

**Comment by koch-t** [comment]
IMO this should be handled by the integration system feeding the data via GTFS to RRRR>
