### ISSUE TITLE
undefined reference sdl_main

### ISSUE THREAD

**Issue by vinzentt** [bliksemlabs/rrrr#153]
Hi,

when compiling using clang (after installing I hope all needed dependencies) i have this error when launching the make:
rrrr/tester-viz.c:162: undefined reference « sdl_main »
clang: error: linker command failed with exit code 1

Looking at the code, it looks like it is defined above in this file. Any idea?

Thanks.

Vincent

**Comment by skinkie** [comment]
Take the ANSI branch ;)

**Comment by vinzentt** [comment]
Now I have this: 
clang: error: no such file or directory: 'gtfs-realtime.pb-c.c'

but i compiled the app by removing from makefile tester-viz

**Comment by skinkie** [comment]
In the ansi branch first type make all that will generate the protobuf c 
file once.
