### ISSUE TITLE
IntSet initialization mistake

### ISSUE THREAD

**Issue by abyrd** [bliksemlabs/rrrr#156]
IntSet_new calls IntSet_clear, which assumes that all the list head pointers are already initialized to NULL. Freeing the collision-lists and initializing should be in separate functions. This is fixed in some code I have locally, where IntSet becomes a map from int64_t to uint32_t, i.e. a map from OSM IDs to positive integer indexes.

Really we should pull all this code out into a libbliksem, along with my PBF loader code. See #155.

**Comment by koch-t** [comment]
It was moved to https://github.com/conveyal/vanilla-extract
