### ISSUE TITLE
router_result_dump contains deps on negative values

### ISSUE THREAD

**Issue by skinkie** [bliksemlabs/rrrr#17]
https://github.com/abyrd/rrrr/blob/migrate_stdint/router.c#L370

Which in essence shows that last_stop could stay negative, which has a very bad affect on: tdata_stop_id_for_index in the line below.

**Comment by skinkie** [comment]
Something like this?

diff --git a/router.c b/router.c
index 0f7909c..702be23 100644
--- a/router.c
+++ b/router.c
@@ -367,7 +367,7 @@ uint32_t router_result_dump(router_t *prouter, router_request_t *preq, char *buf
             } 
             //b += sprintf (b, "round %d  ", round);
             uint32_t last_stop = states[s].back_stop;
-            if (s < 0 || s > router.tdata.n_stops) { 
-            if (last_stop == NONE || s == NONE || s > router.tdata.n_stops) { 
               // this was causing segfaults
               b += sprintf (b, "neg stopid %d\n", s);
               break;

**Comment by abyrd** [comment]
Actually it's redundant since NONE is the max integer. Just do > nstops, which will include and special values on a uint.

-a

Stefan de Konink notifications@github.com a écrit :

> Something like this?
> 
> diff --git a/router.c b/router.c
> index 0f7909c..702be23 100644
> --- a/router.c
> +++ b/router.c
> @@ -367,7 +367,7 @@ uint32_t router_result_dump(router_t *prouter,
> router_request_t *preq, char *buf
>             } 
>             //b += sprintf (b, "round %d  ", round);
>             uint32_t last_stop = states[s].back_stop;
> -            if (s < 0 || s > router.tdata.n_stops) { 
> -            if (last_stop == NONE || s == NONE || s >
>   router.tdata.n_stops) { 
>               // this was causing segfaults
>               b += sprintf (b, "neg stopid %d\n", s);
>               break;
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/abyrd/rrrr/issues/17#issuecomment-21246400

Andrew

## 

Sent from a device without a keyboard. Please excuse my brevity and any absurd auto-correct errors.

**Comment by abyrd** [comment]
I am adding code to interpret epoch times as date&time, and apply the datemask.

Stefan de Konink notifications@github.com a écrit :

> Something like this?
> 
> diff --git a/router.c b/router.c
> index 0f7909c..702be23 100644
> --- a/router.c
> +++ b/router.c
> @@ -367,7 +367,7 @@ uint32_t router_result_dump(router_t *prouter,
> router_request_t *preq, char *buf
>             } 
>             //b += sprintf (b, "round %d  ", round);
>             uint32_t last_stop = states[s].back_stop;
> -            if (s < 0 || s > router.tdata.n_stops) { 
> -            if (last_stop == NONE || s == NONE || s >
>   router.tdata.n_stops) { 
>               // this was causing segfaults
>               b += sprintf (b, "neg stopid %d\n", s);
>               break;
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/abyrd/rrrr/issues/17#issuecomment-21246400

Andrew

## 

Sent from a device without a keyboard. Please excuse my brevity and any absurd auto-correct errors.
