### ISSUE TITLE
Itinerary from and to the same stop crash the router.

### ISSUE THREAD

**Issue by koch-t** [bliksemlabs/rrrr#22]
-- Router Request --
from:  Stop 1a2 [1]
to:    Stop 1a2 [1]
time:  14:59:36 [53978]
speed: 1.500000 m/sec
arrive-by: false
max xfers: 5
max time:     --   

Itinerary from and to the same stop crash the router.

**Comment by abyrd** [comment]
We need to be able to report common error conditions in the response. This one would presumably just be detected by a quick check at the beginning before routing.
