### ISSUE TITLE
Unpossible Itinerary crashes router

### ISSUE THREAD

**Issue by koch-t** [bliksemlabs/rrrr#23]
If you plan a trip that is really not possible, such as a trip between two unconnected islands crashes the router, there is no proper error handling

**Comment by skinkie** [comment]
Should we validate the input of the router function, or should be validate the input prior to entering the routing function. I see that the routing code (when called multiple times) does some extra work that shouldn't have been done. My guess is that the public "safe" function should validate (hence the first routing call), and the internal function should be used for the reversal.

**Comment by abyrd** [comment]
Thomas specifically evokes routing between isolated islands. I don't see a way/reason to validate that before issuing the request. Even if it were possible, the router still should not crash when no path is found.
