### ISSUE TITLE
Reversal routing and (transitive/symetric) transfers

### ISSUE THREAD

**Issue by koch-t** [bliksemlabs/rrrr#25]
Currently our planner has issues with unidirectional transfers, because it can not do the reverse search without having the reverse transfer available. We should figure out if our transfers should in general be transitive, if not: generate both as workaround, or design a way to scan through all transfers.

Transfers are unidirectional, currently(?) rrr uses from_stop_id wrongly when reversing a search request.

**Comment by skinkie** [comment]
We decide that all transfers must be symmetric. We should document this "limitation" in the planner features.
