### ISSUE TITLE
2c: add parentstation relationships as transfers

### ISSUE THREAD

**Issue by skinkie** [bliksemlabs/rrrr#30]
transfers.txt are currently handled, but there is another case of data inside gtfs which tells something about transfers between stops.
1. we could ignore stops were we have parent stops for
2. we could add transfers between all stops in a parent stops [transitive]
3. we could make a parent stop as special transfer [transitive]

**Comment by koch-t** [comment]
Not sure if this is good idea. Parent_stations/stopareas suck and we need
distances anyway.

**Comment by abyrd** [comment]
Parentstations are useful information but do not allow us to deduce anything about distances to walk between stopplaces within the stoparea.

**Comment by skinkie** [comment]
Not required anymore. 2c contains transfers between 1-4 and 3-5.
