### ISSUE TITLE
Check if "vleugentreinen" are handled okay.

### ISSUE THREAD

**Issue by koch-t** [bliksemlabs/rrrr#4]
It's explained here http://en.wikipedia.org/wiki/Portion_working

Sections of train's merged together at several locations and at a later stage they split again. There aren't many left (I think Gouda in the weekends still?), they should be indicated by the block_id. 
Block_id in the NS feed always indicates a single train (the steel version) doing a route along 1 or more trip_id's.

**Comment by abyrd** [comment]
So this is a case where we might need block-transfers (onboard costless change of tripid) but the trips within a single block are not necessarily connected together at their ends -- they might be connected somewhere in the middle.

That assumes that one of the constituent half-trains keeps its tripid when it joins the other. In the case that both half-trains lose their tripid and take on another third tripid, then all trips are connected together into blocks at their ends, but we have Y-shaped connections of trips.

**Comment by abyrd** [comment]
Closely related to #79 block transfers.

**Comment by koch-t** [comment]
In the way i export GTFS now there are just duplicate trips. Each block where you can go from a to c has it's own sequence of tripid's in that block. Thus the same segment of a tran is referred to by multiple trip_id's. The latter is giving me some headaches when applying realtime however.
Thus a simple implementation of #79 would currently suffice, but i'm playing with the option to deduplicate trip's and create block-transfers using trip-to-trip transfers with a new to propose transfer_type.

**Comment by koch-t** [comment]
Fixed in #185 #186
