### ISSUE TITLE
Lelystad to Den Haag Moerwijk

### ISSUE THREAD

**Issue by skinkie** [bliksemlabs/rrrr#40]
When planning a trip from station Lelystad to Den Haag Moerwijk there is a direct train available at a very late time in the evening. In reversal this very late train is preferred over the arrival of the first search.

This might indicate some specific problem.

**Comment by abyrd** [comment]
At the very least this is a reminder that we should not be reporting only the results of the final double-reversed search, but also best-effort compacted version of those from earlier passes.

**Comment by skinkie** [comment]
Shouldn't we bound the offset in the reversal only to earlier and equal arriving trips? I don't get why this is a pareto optimal result.

**Comment by abyrd** [comment]
Yes we should. The bounding is already implemented based on the best known arrival time to the destination, but not according to the bounds in the request. i.e. The bounds in the request are set by the reversal function, but not respected by the router. The reason is simply that converting from epoch to rtime and back is error prone and ugly. I can easily enforce the bounding when rtimes are used in the request struct (and this could also make the search a lot faster). This will have an immediate positive effect on result quality and is not complex, so I will try to implement it this week.

**Comment by skinkie** [comment]
Although I agree with the above, I don't see how the actual case depends on the request structure.

Isn't the issue:
forward: req.departure - first.arrival
backward: first.arrival - maximum.departure given first.arrival

I think that the backward step goes wrong isn't it?

**Comment by abyrd** [comment]
I don't understand your previous comment. Are the units time? Do the dashes indicate subtraction or ranges? Note that the bounding is not be done by duration, but by absolute rtime. 

I was about to speculate that this was a problem with reversing a +1 day time. However I actually ran the request on a phone and on current code, and it only fails on the phone. The current master gives:

```
./testerrrr 586 1167 D 2013-08-02T11:00
-- Router Request --
from:  Lelystad, Station Centrum [586]
to:    Den Haag, Station Moerwijk [1167]
date:  2013-08-02
time:  12:00:00 [1375437600]
speed: 1.500000 m/sec
arrive-by: false
max xfers: 5
max time:     --   

ITIN 1 rides 
WALK    -2  -2   586 39890 12:00:00 12:01:24 +0.0 ;walk;walk;Lelystad, Station Centrum;Lelystad Centrum
RIDE  6861   0 39890 20326 23:15:00 00:57:00 +1D +0.0 ;train;Intercity;Dordrecht;Lelystad Centrum;Den Haag Moerwijk
WALK    -2  -2 20326  1167 00:57:00 +1D 00:58:56 +1D +0.0 ;walk;walk;Den Haag Moerwijk;Den Haag, Station Moerwijk

ITIN 2 rides 
WALK    -2  -2   586 39890 12:00:00 12:01:24 +0.0 ;walk;walk;Lelystad, Station Centrum;Lelystad Centrum
RIDE  7088  10 39890 40223 12:11:00 13:26:00 +0.0 ;train;Intercity;Den Haag Centraal;Lelystad Centrum;Den Haag Centraal
WALK    -2  -2 40223 40220 13:26:00 13:26:52 +0.0 ;walk;walk;Den Haag Centraal;Den Haag Centraal
RIDE 12550  12 40220 20326 13:28:00 13:36:00 +0.0 ;train;Sprinter;Dordrecht;Den Haag Centraal;Den Haag Moerwijk
WALK    -2  -2 20326  1167 13:36:00 13:37:56 +0.0 ;walk;walk;Den Haag Moerwijk;Den Haag, Station Moerwijk
Repeating search with reversed request: 
-- Router Request --
from:  Lelystad, Station Centrum [586]
to:    Den Haag, Station Moerwijk [1167]
date:  2013-08-02
time:  13:37:56 [1375443476]
speed: 1.500000 m/sec
arrive-by: true
max xfers: 1
max time:  15:56:16 +1D

ITIN 1 rides 
WALK    -2  -2   586 39890 23:13:36 -1D 23:15:00 -1D +0.0 ;walk;walk;Lelystad, Station Centrum;Lelystad Centrum
RIDE  1379   1 39890 20326 23:15:00 -1D 00:57:00 +0.0 ;train;Intercity;Dordrecht;Lelystad Centrum;Den Haag Moerwijk
WALK    -2  -2 20326  1167 13:36:00 13:37:56 +0.0 ;walk;walk;Den Haag Moerwijk;Den Haag, Station Moerwijk

ITIN 2 rides 
WALK    -2  -2   586 39890 12:09:36 12:11:00 +0.0 ;walk;walk;Lelystad, Station Centrum;Lelystad Centrum
RIDE  7088  10 39890 40223 12:11:00 13:26:00 +0.0 ;train;Intercity;Den Haag Centraal;Lelystad Centrum;Den Haag Centraal
WALK    -2  -2 40223 40220 13:27:08 13:28:00 +0.0 ;walk;walk;Den Haag Centraal;Den Haag Centraal
RIDE 12550  12 40220 20326 13:28:00 13:36:00 +0.0 ;train;Sprinter;Dordrecht;Den Haag Centraal;Den Haag Moerwijk
WALK    -2  -2 20326  1167 13:36:00 13:37:56 +0.0 ;walk;walk;Den Haag Moerwijk;Den Haag, Station Moerwijk
Repeating search with reversed request: 
-- Router Request --
from:  Lelystad, Station Centrum [586]
to:    Den Haag, Station Moerwijk [1167]
date:  2013-08-02
time:  12:09:36 [1375438176]
speed: 1.500000 m/sec
arrive-by: false
max xfers: 1
max time:  17:34:12 +1D

ITIN 1 rides 
WALK    -2  -2   586 39890 12:09:36 12:11:00 +0.0 ;walk;walk;Lelystad, Station Centrum;Lelystad Centrum
RIDE  6861   0 39890 20326 23:15:00 00:57:00 +1D +0.0 ;train;Intercity;Dordrecht;Lelystad Centrum;Den Haag Moerwijk
WALK    -2  -2 20326  1167 00:57:00 +1D 00:58:56 +1D +0.0 ;walk;walk;Den Haag Moerwijk;Den Haag, Station Moerwijk

ITIN 2 rides 
WALK    -2  -2   586 39890 12:09:36 12:11:00 +0.0 ;walk;walk;Lelystad, Station Centrum;Lelystad Centrum
RIDE  7088  10 39890 40223 12:11:00 13:26:00 +0.0 ;train;Intercity;Den Haag Centraal;Lelystad Centrum;Den Haag Centraal
WALK    -2  -2 40223 40220 13:26:00 13:26:52 +0.0 ;walk;walk;Den Haag Centraal;Den Haag Centraal
RIDE 12550  12 40220 20326 13:28:00 13:36:00 +0.0 ;train;Sprinter;Dordrecht;Den Haag Centraal;Den Haag Moerwijk
WALK    -2  -2 20326  1167 13:36:00 13:37:56 +0.0 ;walk;walk;Den Haag Moerwijk;Den Haag, Station Moerwijk
```

So maybe this is a problem that has been fixed already.

**Comment by koch-t** [comment]
This problem also occurs on Lelystad -> Utrecht which has a few non-stop services on the start and end of the serviceday.

**Comment by koch-t** [comment]
Seems fixed in master now.
TOOD write test with 1 stop service in early-morning and late-night and a 2 stop service at 12:00. Check if 12:00 service is taken
