### ISSUE TITLE
implement a cost function to evaluate preferences against

### ISSUE THREAD

**Issue by skinkie** [bliksemlabs/rrrr#54]
We need to implement a cost function that potentially lowers the cost of a transfer based on route and trip attributes or user preferences regarding stop transfers.

**Comment by abyrd** [comment]
Raptor does not use a cost function or store a cost. This would mean really changing the implementation. I suppose it would mean adding another dimension to the pareto optimality.

**Comment by skinkie** [comment]
In my opinion you can delay this as long as possible. Lowest priority.

**Comment by skinkie** [comment]
2e can be solved in a different way, removing the testset label.

**Comment by skinkie** [comment]
Should be implemented with #77
