### ISSUE TITLE
3f: implement banning-stop-hard

### ISSUE THREAD

**Issue by skinkie** [bliksemlabs/rrrr#58]
Jaap gave me the reasoning about this. Basically what this functionality should do is prevent that a stop is passed in a route. The route itself is allowed before that point and after that point.

```
A - B - C - D - E
  F - G - H - I
```

So by excluding C a route from A to E could flow from A - B - G - H - D - E

**Comment by abyrd** [comment]
This should be as simple as resetting the current trip to NONE when we spot the banned stop.To avoid all dynamic allocation issues etc. let's implement stop banning with lists of size 1 and then expand when the method is shown to work.

**Comment by skinkie** [comment]
Is it that simple? Wouldn't that exclude the entire trip opposed just the two edges that connect C to B and D?

**Comment by abyrd** [comment]
No, when the trip is NONE it should attempt to re-board. Should work.

**Comment by abyrd** [comment]
Why is this called banning-stop-hard? Does that refer to the fact that we cannot pass through the stop at all? Would soft stop banning then just mean you cannot alight or transfer at a stop, but can ride through it?

**Comment by skinkie** [comment]
It was the name Jaap used in OpenTripPlanner. And yes the 'soft' version would just prevent alight/boarding, which is implemented already.
