### ISSUE TITLE
trip descriptor match from gtfs and start_date

### ISSUE THREAD

**Issue by skinkie** [bliksemlabs/rrrr#60]
Currently we use a radix tree to find the tripid, but a start_date is also present. An alteration should therefore only be applied in routing when this also matches.

**Comment by skinkie** [comment]
@abyrd will implement rtime_to_date and rtime_to_epoch. Want both, makes it less error prone.

**Comment by abyrd** [comment]
The remaining real reason we need epoch time helper functions at all: GTFS-RT messages use epoch time to specify validity range.

**Comment by skinkie** [comment]
https://developers.google.com/transit/gtfs-realtime/reference#TripDescriptor

**Comment by abyrd** [comment]
Merging into #61 . EntitySelectors can include tripDescriptors, so we're selecting on a route/trip/time basis.
