### ISSUE TITLE
more optimised guaranteed transfers handling

### ISSUE THREAD

**Issue by skinkie** [bliksemlabs/rrrr#69]
Andrew: 
now that we have separate states for transit and walk arrival times we can much more effectively implement guaranteed transfers
upon boarding a trip, we can look up whether the combination is guaranteed or not, and use the previous transit arrival time instead of the walk one if it's guaranteed.
thereby ignoring all walk time.

**Comment by abyrd** [comment]
Closing because #3 is starting to cover the same subject.
