### ISSUE TITLE
Current planning glitches

### ISSUE THREAD

**Issue by skinkie** [bliksemlabs/rrrr#74]
Planning with the latest android app of @skywave 

From: Voorburg
To: Utrecht Centraal

24 sep 2013

Arrive by 11:00; shows only the Sprinter from 10:01 to Utrecht, no transfers.
It seems that the planner doesn't count 11:00 arrive by as the trip results arrive at 11:00.

When planning for Arrive By 11:01, I do get the Sprinter and Intercity option.

But the even more interesting case why doesn't the router suggest:
Taking the Sprinter at 10:01, transfer to the Intercity and arrive 15 minutes early?

I could consider that given that I would plan for 9:59 this would be "ok" just one train, no transfers, everything will be "ok" and the solution could still be considered "well found".

**Comment by koch-t** [comment]
Issue "expired" code has been changed too much
