### ISSUE TITLE
return suboptimal trips

### ISSUE THREAD

**Issue by abyrd** [bliksemlabs/rrrr#78]
Planning from Rotterdam Centraal to Delft, Molengraafsingel (Yes Delft), Bliksem gives excellent advice to take a SPR to Delft Zuid then walk all the way to Yes. However, we do not get the obvious 2-trip option of riding to Delft Central and taking bus 69. This is because the second option is not optimal in terms of time or transfers, but uses a lot less walking.

Two options: produce suboptimal trips, or include walk distance as a dimension in Pareto dominance.

The latter option is outlined in sec 4.1 of the paper (McRAPTOR) but makes the number of states essentially unlimited and needs lots of dynamic allocation. I almost see A\* performing better for this kind of search. 

The other option would be to allow a certain amount of slack, with trips that are up to 30 minutes worse than the best known one being stored. This should provide the expected SPR->Bus combination.

**Comment by abyrd** [comment]
This problem is aggravated by our current single-option reversal process. Even if the forward pass finds several options, a reversal based only on the fastest option will throw some of them out. See #81.

**Comment by koch-t** [comment]
Addressed in branch tdata4
