### ISSUE TITLE
Block Transfers

### ISSUE THREAD

**Issue by abyrd** [bliksemlabs/rrrr#79]
By "block transfers" we mean chaining together trips that have the same blockid such that one can "transfer" between them at no cost, expense, or loss of time.

Stefan mentions that in NL only NS might do chaining of trips in this way, and it is not commonly done. It is common in other places but that work would be out of scope for the Netherlands. @skywave can you confirm that the NL dataset does not contain any critical block-transfers?

**Comment by koch-t** [comment]
There are very few vleugeltreinen in the current train-timteable as of this year but still quite a few blocktransfers where a train continues as a different train.

**Comment by abyrd** [comment]
And so we are currently failing on those block transfers then, or at least counting them as a transfer when the ride should continue uninterrupted. I think the solution is to add a single field to each trip indicating the continuing trip. RAPTOR will easily chain onto the next trip, but it will get ugly if we fleugeltrein it.

**Comment by koch-t** [comment]
It's counted as a transfer. AFAIK at this point it will just recommend to get on board the same right now as slacktime is 0.

**Comment by koch-t** [comment]
Fixed in Tdata #185 #186
