### ISSUE TITLE
UI: tapping walk link opens transfer map

### ISSUE THREAD

**Issue by abyrd** [bliksemlabs/rrrr#80]
Map-based interface is not necessarily useful in general, but would help the passenger identify how to walk to make a transfer between two unfamiliar stops.

Maybe just open a google maps / OSM page with markers on the two stop locations and a single straight-line arrow (from->to).

**Comment by koch-t** [comment]
I'm currently throwing a nearestneigbbour matrix of stops with d <= 2 kilometers through OTP. I'm storing the true distance and the encoded polyline for debugging purposes (and a little bit because i wanted this too ;) ) . This should definitely be do-able.

**Comment by koch-t** [comment]
Well there's the OTP render...
