### ISSUE TITLE
When reversing, retain some slower itineraries

### ISSUE THREAD

**Issue by abyrd** [bliksemlabs/rrrr#81]
Even if the first router pass finds several options, the reversed request is based only on the fastest option found. This will of course throw out some potentially suboptimal but interesting results.

Really we should make a reversed request based on _each_ itinerary found in the first pass, re run all of those, and accumulate all results found at any stage.

The results of first or second-generation searches that are in reverse-chronological order should then be reversed (simply re-traversing the same routes rather than re-searching).

This should give a lot more different options.

**Comment by abyrd** [comment]
Depends on #82, a faster/constrained reversal function.

**Comment by koch-t** [comment]
Adressed in branch tdata4
