### ISSUE TITLE
Android client needs reinitialization after phone sleeps

### ISSUE THREAD

**Issue by abyrd** [bliksemlabs/rrrr#83]
@skywave Stefan says you are aware of this one, so I'm just creating a ticket for the known issue. When returning to the Bliksem app, if from and to are not re-entered a seemingly random search result is produced.

**Comment by koch-t** [comment]
Bliksem4android should get it's own issue tracker and stop hijacking this one ;)

**Comment by abyrd** [comment]
So I guess the Android project does have a bug reporting forum -- do you want such comments to be made there?

**Comment by koch-t** [comment]
Not it doesn't have it's own bug reporting forum. Not sure if needed
either..

**Comment by abyrd** [comment]
OK just checking what you meant.
