### ISSUE TITLE
Show intermediate stops.

### ISSUE THREAD

**Issue by koch-t** [bliksemlabs/rrrr#84]
Useful for debugging and fits nicely in otp_output. Will also be a feature needed by some travellers.

**Comment by joelhaasnoot** [comment]
While you're looking up the trip, we'd also be interested in the whole trip (OTP just does intermediate stops I believe.)

**Comment by koch-t** [comment]
Could be interesting for some layout's to show extra transfer possibilities indeed.

**Comment by skinkie** [comment]
Fix in 6f0a0418d398d77a63f15d32d5bfd04cae93fc7f

**Comment by koch-t** [comment]
To save precious bandwith it's "convenient" to make intermediateStops optional.
