### ISSUE TITLE
rrrrealtime broken

### ISSUE THREAD

**Issue by koch-t** [bliksemlabs/rrrr#88]
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
Attempt to insert 0-length string.
[1380661376:4461] NOTICE: Initial logging level 7
[1380661376:4461] NOTICE: Library version: 1.3 6c58228
[1380661376:4461] NOTICE:  Started with daemon pid 0
[1380661376:4461] NOTICE:  static allocation: 4488 + (16 x 1024 fds) = 20872 bytes
[1380661376:4462] NOTICE:  canonical_hostname = openkvk.nl
websocket connections opened
rx 10240 bytes: frame exceeds maximum allowed frame length

rx 10240 bytes: frame exceeds maximum allowed frame length

rx 10240 bytes: frame exceeds maximum allowed frame length

rx 10240 bytes: frame exceeds maximum allowed frame length

rx 10240 bytes: frame exceeds maximum allowed frame length

rx 10240 bytes: frame exceeds maximum allowed frame length

rx 10240 bytes: frame exceeds maximum allowed frame length

rx 10240 bytes: frame exceeds maximum allowed frame length

rx 10240 bytes: frame exceeds maximum allowed frame length

rx 10240 bytes: frame exceeds maximum allowed frame length

rx 10240 bytes: frame exceeds maximum allowed frame length

rx 10240 bytes: frame exceeds maximum allowed frame length

rx 7101 bytes: final frame, single-frame message. message 'transit_realtime.FeedHeader': missing required field 'gtfs_realtime_version'
error parsing member _unknown-field_ of transit_realtime.FeedMessage
error unpacking incoming gtfs-rt message

**Comment by skinkie** [comment]
Radixtree fixed in 97080f812597480a98d46ce65cfed3967b007709

But there is still a segfault:

rx 4800 bytes: final frame, single-frame message. message 'transit_realtime.FeedMessage': missing required field 'header'
Segmentation fault

**Comment by abyrd** [comment]
Yeah this is due to the zero-terminated vs fixed width problem.
