### ISSUE TITLE
first leg board time shifts

### ISSUE THREAD

**Issue by abyrd** [bliksemlabs/rrrr#9]
From @skinkie  via email:
I just planned 16:55 from Voorburg, Voorburg Station to Rozenrust. It gives me the option to get on bus 45 to Leiden CS at 17:27. When I modify it to 16:54 my option changes to leaving at 17:12. I have to move it back to 16:39 to get the best departure at 16:57.

**Comment by skinkie** [comment]
Its not really the 'start time' the walking time (1 min) is accounted for.

**Comment by abyrd** [comment]
Fixed title.
