### ISSUE TITLE
polyline encoder glitches

### ISSUE THREAD

**Issue by abyrd** [bliksemlabs/rrrr#96]
Here is an example:

```
_yltGn_llVp]bVjMrV~GbVzAfLrEb\\~A~^lDl_@nGl^bId_@xF|X}Iv@oPDm\\Dsa@~~~~~^qNRc[UaK~~~~~^uUJwSFeR?}OMmSHiSB}W?cUDaOCqMFdC{U}IeC~MgJxBmMiWi_@
```

The strings of tildes are the glitches. See resulting coordinates in:
https://developers.google.com/maps/documentation/utilities/polylineutility

**Comment by koch-t** [comment]
It's even worse on ARM btw. There almost every polyline has lot's of
tildes. Thus possible also 32bit.

**Comment by koch-t** [comment]
Fixed in tdata4 and polyline code now under test-coverage
